### ISSUE TITLE
Missing Python environment in MRChem docker image

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/metamr#3]
I'm currently not able to run `mrchem` in the docker image due to a missing `pathlib` module

**Comment by stigrj** [comment]
@robertodr in order to get the correct environment (`pathlib`, `parselglossy` etc) inside the docker image I have to do
```
$ cd /mrchem
$ pipenv install
$ pipenv shell
```
How can we setup this environment globally in the image?

**Comment by robertodr** [comment]
I think I left it like that to leave the user freedom to set up their own environment (maybe they don't want to use Pipenv) Maybe we can print a message on login?

**Comment by stigrj** [comment]
I also get permission problems. The `mrchem` script creates some empty directories (`orbitals`, `initial_guess`, etc) as well as the input intermediate `mrchem.json`. Why do we need root access to do this in the image?

**Comment by stigrj** [comment]
Hmm, it's the example directories `~/work/h2o_energy_blyp` in the image that get root ownership from the `entrypoint` script. Do you know how to avoid this?

**Comment by stigrj** [comment]
Never mind, there's a `chown -R` just a bit too early in the script :slightly_smiling_face:

**Comment by robertodr** [comment]
I admit I was lazy and just did the minimum needed to get the tagged
version to compile on the Docker Hub builder bot :)
